### ISSUE TITLE
并发高时TradeId可能会重复 建议处理一下

### ISSUE THREAD

**Issue by zhzhwcn** [vnpy/vnpy_sopt#5]
以下为c++打出来的日志

> OnRspQryTrade:BrokerID:6666,BrokerOrderSeq:1440,OrderLocalID:Aa80001532,InstrumentID:10004510,Direction:卖,Volume:2,Price:0.048800,OrderSysID:4054287,OrderRef:462,ExchangeID:SSE,TradeTime:09:47:05,ClientID:B884955400,InvestUnitID:,TradeId:           195674
OnRspQryTrade:BrokerID:6666,BrokerOrderSeq:1440,OrderLocalID:Aa80001532,InstrumentID:10004510,Direction:卖,Volume:3,Price:0.048800,OrderSysID:4054287,OrderRef:462,ExchangeID:SSE,TradeTime:09:47:05,ClientID:B884955400,InvestUnitID:,TradeId:           195673
OnRspQryTrade:BrokerID:6666,BrokerOrderSeq:1570,OrderLocalID:Aa80001651,InstrumentID:10004510,Direction:买,Volume:3,Price:0.048800,OrderSysID:4597414,OrderRef:503,ExchangeID:SSE,TradeTime:09:47:05,ClientID:B884955400,InvestUnitID:,TradeId:           195673
OnRspQryTrade:BrokerID:6666,BrokerOrderSeq:1570,OrderLocalID:Aa80001651,InstrumentID:10004510,Direction:买,Volume:1,Price:0.048800,OrderSysID:4597414,OrderRef:503,ExchangeID:SSE,TradeTime:09:47:05,ClientID:B884955400,InvestUnitID:,TradeId:           195672

有两个195673

**Comment by vnpy** [comment]
这种情况是发生自成交了导致的吧

**Comment by zhzhwcn** [comment]
但是由于这里的代码用的是vt_tradeid做为了key，所以实际上会丢掉前一条数据
https://github.com/vnpy/vnpy/blob/master/vnpy/trader/engine.py#L411
